# Does this project really need a Docker compose file?
# Not currently. But I'm too lazy to actually write the proper docker run syntax so whatever
version: "3.8"
services:
  bot:
    read_only: true
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./app/cbt:/cbt
      - ./config.yaml:/config/config.yaml
    command: ["python3", "main.py"]