# Does this project really need a Docker compose file?
# Not currently. But I'm too lazy to actually write the proper docker run syntax so whatever
version: "3.8"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./app/cbt:/cbt
    command: ["python3", "main.py"]
  discorddata_backend:
    image: harbor.nicleary.com/library/discord-metrics-server-api:29
    environment:
      MARIA_USER: mysql
      MARIA_PASSWORD: mysql
      MARIA_PORT: 3306
      MARIA_DB: discorddata
      MARIA_HOST: discorddata_db
    ports:
      - 8080:8080
    depends_on:
      discorddata_atlas_run_migrations:
        condition: service_completed_successfully
  discorddata_atlas_run_migrations:
    image: harbor.nicleary.com/library/discord-metrics-server-migrations:29
    entrypoint:
      - "atlas"
      - "migrate"
      - "apply"
      - "--dir"
      - "file://ent/migrate/migrations"
      - "--url"
      - "mysql://mysql:mysql@discorddata_db:3306/discorddata"
    depends_on:
      discorddata_db:
        condition: service_healthy
  discorddata_db:
    image: mariadb
    restart: always
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: discorddata
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MARIADB_MYSQL_LOCALHOST_USER: 1
      MARIADB_MYSQL_LOCALHOST_GRANTS: USAGE
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 1s
      timeout: 2s
      retries: 3

volumes:
  mariadb_data: