# Configuration for where to find the libretranslate server
libretranslate_server_config:
  default_language: "en"
  url: "https://translate.nicleary.com/"

# The ID of your discord test server
discord_server_id: 725357725546053685
# The below are all optional, but if not provided, must be configured as {}, like how the jenkins config is setup
all_memes_config:
  prophet_has_spoken:
    # Which users to trigger on
    users:
      - 475488656170156039
    # Which channels to configure on
    channels:
      - 725357726133125223
  emacs_quotes:
    users:
      - 475488656170156039
  guix_quotes:
    users:
      - 475488656170156039
  devops_quotes: {}
  jenkins: {}
  caustic: {}
  chris: {}
  taytay: {}
github:
  owner: NickClearyTech
  repo: clearys-bot-toy
  workflow_name: "Main Action"


# Note that the above configs are for a test server, not the production Suffering Inc server
# For editing the production deploy, simply edit the production_confing.yaml with the relevant values