apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clearybottoy
  name: clearybottoy
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: clearybottoy
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: clearybottoy
    spec:
      containers:
        - image: harbor.nicleary.com/library/clearysbottoy:10
          imagePullPolicy: Always
          command: ['bash', '-c', 'python main.py']
          name: "clearys-bot-toy"
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discordtoken
                  key: discord_token