apiVersion: batch/v1
kind: Job
metadata:
  name: script-runner
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: config-volume
          configMap:
            name: configuration
      containers:
        - image: harbor.nicleary.com/library/discordscriptrunner:2
          imagePullPolicy: Always
          command: [ "python",  "script_runner.py" ]
          name: "discord-script-runner"
          volumeMounts:
            - name: config-volume
              mountPath: /config
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discordtoken
                  key: discord_token
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  key: github_token
                  name: discordtoken
            - name: DISCORD_SERVER
              value: "790420576468205628"
  backoffLimit: 4